### ISSUE TITLE
Inline icons aren't as pretty as they could be

### ISSUE THREAD

**Issue by udf** [udf/spoilerobot#2]
Also using a spoiler of a car as a spoiler is an ambiguous joke which makes it hard for non-native English speakers to get.

**Comment by Lonami** [comment]
Even if it's meant as a joke, an icon doesn't *have* to symbolize something. What other thing represents an "spoiler" as we know it better? How well known would this alternative be?

**Comment by udf** [comment]
Good point, closing this.

**Comment by Lonami** [comment]
I'm good at this thing called "closing issues".

**Comment by udf** [comment]
Make some issues and I'll close them for you
