### ISSUE TITLE
Creating spoilers without /start

### ISSUE THREAD

**Issue by 9ary** [udf/spoilerobot#5]
streetwal ⁣, [24.12.18 14:33]
btw @katewastaken spoilero feature request

samsam, [24.12.18 14:33]
github has issues

streetwal ⁣, [24.12.18 14:33]
it'd be cool if you could create a media spoiler without doing /start

streetwal ⁣, [24.12.18 14:34]
if you just send it a picture if will just tell you to do that

streetwal ⁣, [24.12.18 14:34]
which is gay

samsam, [24.12.18 14:35]
make an issue on the repo so i dont forget about this when i finally gather enough motivation to do it

**Comment by Lonami** [comment]
We'll forget about this here too anyway.

**Comment by 9ary** [comment]
:fire:

**Comment by Faith001** [comment]
25th of May 2019
_They forgot anyway._

**Comment by udf** [comment]
@Faith001 Since you only commented here after I asked a question about this issue, you're the one who forgot.

**Comment by Lonami** [comment]
🔥
